CONFIG_NEWLIB_LIBC=y

CONFIG_MODEM_MODULES=y
CONFIG_MODEM_BACKEND_UART=y
CONFIG_MODEM_CMUX=y
CONFIG_MODEM_PIPE=y
CONFIG_MODEM_CHAT=y
CONFIG_MODEM_PPP=y

CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_NETWORKING=y
CONFIG_NET_L2_PPP=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_STATISTICS=y

CONFIG_SHELL=y
CONFIG_NET_SHELL=y
CONFIG_LOG=y

CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=65536